---
title: "Teleportation"
output: 
  html_document:
    css: "style.css"
---

#### 10/23/2020

---

Teleportation is an interesting thing, and would definitely be very cool. The issue arises, however, whenever someone attempts to think about how it would scientifically be done. 

There are a couple issues with the scientific interpretation of teleportation. The surface level ones are mainly things that need to be taken into account, which can't physically be measured.

If you are teleporting from location A to location B, you need to know:

* The actual positions of location A and location B, for obvious reasons
* The different speeds at which one would be traveling at locations A and B, so that you don't end up in a scenario like the one described below

The scenario in which speeds would be an issue is the one in which you are teleporting from somewhere in, say, the Sahara Desert (which is close to the equator) to somewhere in Antarctica (somewhere far from the equator). Let us for the sake of convenience consider the Earth to not be moving relatively to any other bodies, and only rotating. Then, at the equator, you are traveling around [1000 miles per hour](https://www.scientificamerican.com/article/how-fast-is-the-earth-mov/#:~:text=The%20earth%20rotates%20once%20every,roughly%201%2C000%20miles%20per%20hour.), while at the poles, you are traveling [significantly slower](https://www.thoughtco.com/speed-of-the-earth-1435093) (effectively zero for our closed-system Earth). If you were to be teleported from our A of the Sahara Desert to our B of Antarctica, you would find yourself moving about 1000 miles per hour too quickly and would swiftly die.

Now let's backtrack to our first thing we need to know. What are the exact positions of A and B? We can't really measure anything very well, unless it's relatively (compared to a point of reference on Earth) whose accuracy may be questionable. In order to ensure that a mistake is not made, our teleportation sensors would have to have location data accurate on an extremely low level. While this is obviously not possible for us today, it won't necessarily be impossible in the future... or so we think. If we have a reference point from which we are measuring, who is to say that said reference point isn't changing its own location? The universe is constantly shifting and turning and dilating and expanding and contracting in ways that we can't imagine due to faraway galaxies and celestial bodies whose impacts we are unaware of. The force of gravity may have an extremely small impact on us if it is from such a faraway celestial body, but it is important to note that it can never be zero (despite its [exponential decay](https://en.wikipedia.org/wiki/Newton%27s_law_of_universal_gravitation) over an increasing distance). This uncertainty could easily impact our calculations in such a way as to render the detailed low-level examination of our teleportation subject useless.

Even if, by some miracle, we manage to deal with the (likely impossible to deal with) issues surrounding the determination of exact locations A and B, we'll need to deal with the other main elephant in the room -- how exactly do we teleport something? There are a couple of possibilities:

* The subject is completely atomized, and these exact atoms are sent to another location where they are reconstructed in the same way as the subject's atomic structure
* The subject is completely atomized, and different atoms are used at another location where they are made to construct a copy of the subject at an atomic level
* We use magic and the subject literally disappears and appears elsewhere

Obviously the third is not an option; we need to vaporize our teleportation subject. However, both of the two methods involving vaporization involve just that -- the literal vaporization of the subject. Now, we get into a difficult subject. If I am to die, and then a copy of me (down to the atom) is made, I am still dead... right? Similarly, the methods of teleportation that our science can come up with are basically the same. If we don't use the same atoms, then we are just killing ourselves and making a copy at a convenient location, which can act exactly like us. We may get into a conversation about the nature of self, and what it really means to exist as an entity; this is beyond the scope of this webpage and frankly, I don't care. All I would personally want to know when I enter the teleportation device is whether I will be vaporized and killed, and a copy of me will be made; or, I will simply be transported to another location. Since the latter seems to require magic of some sort, I don't think that we will be certain of this any time soon.

Anyway, if you've finished reading, you can consider the idea that in every instance of teleportation (or "beaming up") in [Star Trek](https://en.wikipedia.org/wiki/Star_Trek:_The_Original_Series), the characters were being killed voluntarily, and a copy of themselves was being made at an alternate location. How many Captain Kirks and Spocks have died? That is an exercise left to the reader.